
import { Business, User, Service, UserType, Review } from './types';
import { getCategoryImage } from './services/categoryImages';

// Every business account starts with this simulated dollar balance, used to pay for
// neighborhood-targeting costs when publishing or expanding deals. Not real money —
// see the "no real payment processing" note on the Terms page.
export const STARTING_BUSINESS_BALANCE = 500;

// Real Wake County neighborhoods (see public/data/wake-neighborhoods.json), picked as
// recognizable, well-populated seed points so demo data has somewhere real to live.
export const DEMO_NEIGHBORHOOD_IDS = [
  'bedford-at-falls-river-raleigh-3', // Bedford at Falls River, Raleigh
  'carolina-preserve-at-amberly-cary', // Carolina Preserve at Amberly, Cary
  'westford-apex', // Westford, Apex
  'heritage-wake-forest', // Heritage, Wake Forest
  'twelve-oaks-holly-springs', // Twelve Oaks, Holly Springs
  'eagle-ridge-garner', // Eagle Ridge, Garner
  'breckenridge-morrisville', // Breckenridge, Morrisville
  'wendell-falls-wendell', // Wendell Falls, Wendell
];

const PRIMARY_NEIGHBORHOOD_ID = DEMO_NEIGHBORHOOD_IDS[0];

const daysFromNow = (days: number) => new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();

const SIGNUP_ID_POOL = ['user-a', 'user-b', 'user-c', ...Array.from({ length: 20 }).map((_, i) => `mock-user-${i}`)];
const genSignupIds = (count: number): string[] => {
  const n = Math.min(count, SIGNUP_ID_POOL.length, 6);
  return SIGNUP_ID_POOL.slice(0, n);
};

export const CATEGORY_GROUPS = [
  {
    name: 'Cleaning & Maintenance',
    categories: [
      'Carpet Cleaning',
      'Cleaning & Maid Services',
      'Gutter Cleaning',
      'House Cleaning',
      'Power Washing',
      'Window Washing'
    ]
  },
  {
    name: 'Outdoor & Yard',
    categories: [
      'Deck or Porch',
      'Fencing Service',
      'Landscaping',
      'Lawn Service',
      'Pool Maintenance',
      'Tree Service'
    ]
  },
  {
    name: 'Home Systems & Repairs',
    categories: [
      'Electrical',
      'Handyman Service',
      'HVAC Maintenance',
      'Plumbing',
      'Roofing',
      'Solar Panel Installation'
    ]
  },
  {
    name: 'Other Services',
    categories: [
      'Home Security',
      'Interior Design',
      'Moving Services',
      'Painting',
      'Pest Control'
    ]
  }
];

// ==== GENERATED BUSINESSES (auto-generated, see scratchpad/generate_data.js) ====
const GENERATED_BUSINESSES: Business[] = [
  { id: 'b4', name: 'Triangle Carpet Care', logoUrl: getCategoryImage('Carpet Cleaning', 200, 200), description: 'Triangle Carpet Care is a local Wake County business specializing in carpet and upholstery cleaning.', rating: 4.5, reviewCount: 168, galleryPhotoIds: ['1608303588026-884930af2559', '1504148455328-c376907d081c', '1558002038-1055907df827'], highlights: ['Locally Owned'], memberships: ['BBB Accredited Business'], isLicensed: false, amenities: ['Free Estimates', 'Satisfaction Guarantee'] },
  { id: 'b5', name: 'Tidy Triangle Maids', logoUrl: getCategoryImage('Cleaning & Maid Services', 200, 200), description: 'Tidy Triangle Maids is a local Wake County business specializing in residential cleaning and maid services.', rating: 4.8, reviewCount: 170, galleryPhotoIds: ['1586023492125-27b2c045efd7', '1600518464441-9154a4dea21b', '1551782450-a2132b4ba21d'], highlights: ['Woman Owned', 'Eco-Friendly'], memberships: ['Local Chamber of Commerce Member'], isLicensed: false, amenities: ['Satisfaction Guarantee', 'Eco-Friendly Products'] },
  { id: 'b6', name: 'Wake Deck Builders', logoUrl: getCategoryImage('Deck or Porch', 200, 200), description: 'Wake Deck Builders is a local Wake County business specializing in deck and porch restoration.', rating: 4.8, reviewCount: 58, galleryPhotoIds: ['1509391366360-2e959784a276', '1576013551627-0cc20b96c2a7', '1592417817098-8fd3d9eb14a5'], highlights: ['Veteran Owned'], memberships: ['BBB Accredited Business'], isLicensed: true, licenseNumber: 'NC-GC-35302', amenities: ['Free Estimates', 'Warranty Included'] },
  { id: 'b7', name: 'BrightSpark Electric', logoUrl: getCategoryImage('Electrical', 200, 200), description: 'BrightSpark Electric is a local Wake County business specializing in residential electrical work.', rating: 4.3, reviewCount: 162, galleryPhotoIds: ['1581578731548-c64695cc6952', '1632759145351-1d592919f522', '1562259949-e8e7689d7828'], highlights: ['Family Owned'], memberships: ['BBB Accredited Business', 'Local Chamber of Commerce Member'], isLicensed: true, licenseNumber: 'NC-EL-39519', amenities: ['Free Estimates', 'Emergency Service Available', 'Warranty Included'] },
  { id: 'b8', name: 'SecureLine Fencing', logoUrl: getCategoryImage('Fencing Service', 200, 200), description: 'SecureLine Fencing is a local Wake County business specializing in fence installation and repair.', rating: 4.8, reviewCount: 63, galleryPhotoIds: ['1585704032915-c3400ca199e7', '1621905251189-08b45d6a269e', '1517842645767-c639042777db'], highlights: [], memberships: ['Local Chamber of Commerce Member'], isLicensed: true, licenseNumber: 'NC-GC-43736', amenities: ['Free Estimates', 'Warranty Included'] },
  { id: 'b9', name: 'ClearFlow Gutters', logoUrl: getCategoryImage('Gutter Cleaning', 200, 200), description: 'ClearFlow Gutters is a local Wake County business specializing in gutter cleaning and protection.', rating: 4.4, reviewCount: 202, galleryPhotoIds: ['1502082553048-f009c37129b9', '1527515637462-cff94eecc1ac', '1581094288338-2314dddb7ece'], highlights: ['Locally Owned'], memberships: [], isLicensed: false, amenities: ['Free Estimates', 'Satisfaction Guarantee'] },
  { id: 'b10', name: 'FixIt Neighbor Handyman', logoUrl: getCategoryImage('Handyman Service', 200, 200), description: 'FixIt Neighbor Handyman is a local Wake County business specializing in general handyman services.', rating: 4.3, reviewCount: 141, galleryPhotoIds: ['1600607687644-c7171b42498f', '1608303588026-884930af2559', '1504148455328-c376907d081c'], highlights: ['Veteran Owned'], memberships: ['BBB Accredited Business'], isLicensed: false, amenities: ['Free Estimates', 'Satisfaction Guarantee'] },
  { id: 'b11', name: 'GuardPost Security', logoUrl: getCategoryImage('Home Security', 200, 200), description: 'GuardPost Security is a local Wake County business specializing in home security installation.', rating: 4.3, reviewCount: 165, galleryPhotoIds: ['1558002038-1055907df827', '1586023492125-27b2c045efd7', '1600518464441-9154a4dea21b'], highlights: ['Family Owned'], memberships: ['BBB Accredited Business'], isLicensed: true, licenseNumber: 'NC-SEC-56387', amenities: ['Free Estimates', 'Emergency Service Available'] },
  { id: 'b12', name: 'Fresh Start Cleaning Co.', logoUrl: getCategoryImage('House Cleaning', 200, 200), description: 'Fresh Start Cleaning Co. is a local Wake County business specializing in residential house cleaning.', rating: 5, reviewCount: 42, galleryPhotoIds: ['1551782450-a2132b4ba21d', '1509391366360-2e959784a276', '1576013551627-0cc20b96c2a7'], highlights: ['Woman Owned', 'Locally Owned'], memberships: ['Local Chamber of Commerce Member'], isLicensed: false, amenities: ['Satisfaction Guarantee', 'Eco-Friendly Products'] },
  { id: 'b13', name: 'Triangle Air & Heat', logoUrl: getCategoryImage('HVAC Maintenance', 200, 200), description: 'Triangle Air & Heat is a local Wake County business specializing in HVAC maintenance and tune-ups.', rating: 5, reviewCount: 136, galleryPhotoIds: ['1592417817098-8fd3d9eb14a5', '1581578731548-c64695cc6952', '1632759145351-1d592919f522'], highlights: ['Veteran Owned'], memberships: ['BBB Accredited Business', 'Local Chamber of Commerce Member'], isLicensed: true, licenseNumber: 'NC-HV-64821', amenities: ['Free Estimates', 'Emergency Service Available', 'Warranty Included'] },
  { id: 'b14', name: 'Bloom Interior Studio', logoUrl: getCategoryImage('Interior Design', 200, 200), description: 'Bloom Interior Studio is a local Wake County business specializing in interior design consulting.', rating: 4, reviewCount: 165, galleryPhotoIds: ['1562259949-e8e7689d7828', '1585704032915-c3400ca199e7', '1621905251189-08b45d6a269e'], highlights: ['Woman Owned'], memberships: ['Local Chamber of Commerce Member'], isLicensed: false, amenities: ['Free Estimates'] },
  { id: 'b15', name: 'Carolina Land & Garden', logoUrl: getCategoryImage('Landscaping', 200, 200), description: 'Carolina Land & Garden is a local Wake County business specializing in landscaping and yard design.', rating: 4, reviewCount: 237, galleryPhotoIds: ['1517842645767-c639042777db', '1502082553048-f009c37129b9', '1527515637462-cff94eecc1ac'], highlights: ['Family Owned', 'Eco-Friendly'], memberships: ['BBB Accredited Business'], isLicensed: false, amenities: ['Free Estimates', 'Satisfaction Guarantee'] },
  { id: 'b16', name: 'Oak City Movers', logoUrl: getCategoryImage('Moving Services', 200, 200), description: 'Oak City Movers is a local Wake County business specializing in local moving and packing.', rating: 4.8, reviewCount: 197, galleryPhotoIds: ['1581094288338-2314dddb7ece', '1600607687644-c7171b42498f', '1608303588026-884930af2559'], highlights: ['Veteran Owned', 'Family Owned'], memberships: ['BBB Accredited Business'], isLicensed: false, amenities: ['Free Estimates', 'Satisfaction Guarantee'] },
  { id: 'b17', name: 'FreshCoat Painting Co.', logoUrl: getCategoryImage('Painting', 200, 200), description: 'FreshCoat Painting Co. is a local Wake County business specializing in interior and exterior painting.', rating: 4.8, reviewCount: 250, galleryPhotoIds: ['1504148455328-c376907d081c', '1558002038-1055907df827', '1586023492125-27b2c045efd7'], highlights: ['Family Owned'], memberships: ['BBB Accredited Business'], isLicensed: true, licenseNumber: 'NC-GC-81689', amenities: ['Free Estimates', 'Warranty Included'] },
  { id: 'b18', name: 'GuardianBug Pest Control', logoUrl: getCategoryImage('Pest Control', 200, 200), description: 'GuardianBug Pest Control is a local Wake County business specializing in pest control and prevention.', rating: 4.5, reviewCount: 127, galleryPhotoIds: ['1600518464441-9154a4dea21b', '1551782450-a2132b4ba21d', '1509391366360-2e959784a276'], highlights: ['Locally Owned'], memberships: ['BBB Accredited Business', 'Local Chamber of Commerce Member'], isLicensed: true, licenseNumber: 'NC-PC-85906', amenities: ['Free Estimates', 'Satisfaction Guarantee', 'Warranty Included'] },
  { id: 'b19', name: 'FlowRight Plumbing', logoUrl: getCategoryImage('Plumbing', 200, 200), description: 'FlowRight Plumbing is a local Wake County business specializing in residential plumbing.', rating: 4.8, reviewCount: 210, galleryPhotoIds: ['1576013551627-0cc20b96c2a7', '1592417817098-8fd3d9eb14a5', '1581578731548-c64695cc6952'], highlights: ['Veteran Owned'], memberships: ['BBB Accredited Business'], isLicensed: true, licenseNumber: 'NC-PL-90123', amenities: ['Free Estimates', 'Emergency Service Available', 'Warranty Included'] },
  { id: 'b20', name: 'BlastAway Power Washing', logoUrl: getCategoryImage('Power Washing', 200, 200), description: 'BlastAway Power Washing is a local Wake County business specializing in pressure washing services.', rating: 4, reviewCount: 82, galleryPhotoIds: ['1632759145351-1d592919f522', '1562259949-e8e7689d7828', '1585704032915-c3400ca199e7'], highlights: ['Locally Owned'], memberships: [], isLicensed: false, amenities: ['Free Estimates', 'Satisfaction Guarantee'] },
  { id: 'b21', name: 'Summit Roofing Co.', logoUrl: getCategoryImage('Roofing', 200, 200), description: 'Summit Roofing Co. is a local Wake County business specializing in roof inspection and repair.', rating: 4.6, reviewCount: 215, galleryPhotoIds: ['1621905251189-08b45d6a269e', '1517842645767-c639042777db', '1502082553048-f009c37129b9'], highlights: ['Family Owned'], memberships: ['BBB Accredited Business', 'Local Chamber of Commerce Member'], isLicensed: true, licenseNumber: 'NC-RF-98557', amenities: ['Free Estimates', 'Warranty Included', 'Emergency Service Available'] },
  { id: 'b23', name: 'SunHarvest Solar', logoUrl: getCategoryImage('Solar Panel Installation', 200, 200), description: 'SunHarvest Solar is a local Wake County business specializing in solar panel maintenance.', rating: 4.7, reviewCount: 79, galleryPhotoIds: ['1608303588026-884930af2559', '1504148455328-c376907d081c', '1558002038-1055907df827'], highlights: ['Eco-Friendly'], memberships: ['BBB Accredited Business'], isLicensed: true, licenseNumber: 'NC-SOL-16991', amenities: ['Free Estimates', 'Warranty Included'] },
  { id: 'b24', name: 'Heritage Tree Care', logoUrl: getCategoryImage('Tree Service', 200, 200), description: 'Heritage Tree Care is a local Wake County business specializing in tree trimming and removal.', rating: 4, reviewCount: 214, galleryPhotoIds: ['1586023492125-27b2c045efd7', '1600518464441-9154a4dea21b', '1551782450-a2132b4ba21d'], highlights: ['Veteran Owned'], memberships: ['BBB Accredited Business'], isLicensed: true, licenseNumber: 'NC-ARB-21208', amenities: ['Free Estimates', 'Emergency Service Available'] },
  { id: 'b25', name: 'CrystalView Window Cleaning', logoUrl: getCategoryImage('Window Washing', 200, 200), description: 'CrystalView Window Cleaning is a local Wake County business specializing in window cleaning services.', rating: 4.6, reviewCount: 200, galleryPhotoIds: ['1509391366360-2e959784a276', '1576013551627-0cc20b96c2a7', '1592417817098-8fd3d9eb14a5'], highlights: ['Locally Owned'], memberships: [], isLicensed: false, amenities: ['Free Estimates', 'Satisfaction Guarantee'] },
];

// ==== GENERATED SERVICES (auto-generated) ====
const GENERATED_SERVICES: Service[] = [
  { id: 's1', businessId: 'b4', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Stain & Odor Treatment', description: 'Targeted pretreatment for pet stains, spills, and high-traffic wear paths.', category: 'Carpet Cleaning', standardPrice: 158, discountPercentage: 15, requiredSignups: 9, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(6) },
  { id: 's2', businessId: 'b4', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Move-Out Carpet Refresh', description: 'A full carpet clean timed for move-out inspections and new tenants.', category: 'Carpet Cleaning', standardPrice: 205, discountPercentage: 22, requiredSignups: 6, currentSignups: 6, signedUpUserIds: genSignupIds(6), expiresAt: daysFromNow(11) },
  { id: 's3', businessId: 'b4', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Area Rug Cleaning', description: 'Professional off-site cleaning for wool, synthetic, and specialty area rugs.', category: 'Carpet Cleaning', standardPrice: 179, discountPercentage: 20, requiredSignups: 4, currentSignups: 3, signedUpUserIds: genSignupIds(3), expiresAt: daysFromNow(2) },
  { id: 's4', businessId: 'b4', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Whole-Home Carpet Deep Clean', description: 'Hot water extraction cleaning for every carpeted room, lifting embedded dirt and allergens.', category: 'Carpet Cleaning', standardPrice: 167, discountPercentage: 12, requiredSignups: 6, currentSignups: 0, signedUpUserIds: genSignupIds(0), expiresAt: daysFromNow(4) },
  { id: 's5', businessId: 'b5', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Post-Party Cleanup', description: 'Same-week cleanup after hosting, so you don\'t spend your weekend scrubbing.', category: 'Cleaning & Maid Services', standardPrice: 144, discountPercentage: 21, requiredSignups: 5, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(3) },
  { id: 's6', businessId: 'b5', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Recurring Bi-Weekly Cleaning', description: 'A standing bi-weekly visit to keep kitchens, bathrooms, and living areas consistently clean.', category: 'Cleaning & Maid Services', standardPrice: 260, discountPercentage: 19, requiredSignups: 12, currentSignups: 7, signedUpUserIds: genSignupIds(7), expiresAt: daysFromNow(8) },
  { id: 's7', businessId: 'b5', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Move-In Ready Cleaning', description: 'A thorough clean so a new home is spotless before the boxes arrive.', category: 'Cleaning & Maid Services', standardPrice: 195, discountPercentage: 15, requiredSignups: 10, currentSignups: 10, signedUpUserIds: genSignupIds(10), expiresAt: daysFromNow(10) },
  { id: 's8', businessId: 'b5', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'One-Time Deep Clean', description: 'Top-to-bottom detail clean covering baseboards, appliances, and forgotten corners.', category: 'Cleaning & Maid Services', standardPrice: 235, discountPercentage: 21, requiredSignups: 12, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(12) },
  { id: 's9', businessId: 'b6', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Screened Porch Cleaning', description: 'Screen, floor, and furniture cleaning to get your porch guest-ready.', category: 'Deck or Porch', standardPrice: 341, discountPercentage: 19, requiredSignups: 12, currentSignups: 12, signedUpUserIds: genSignupIds(12), expiresAt: daysFromNow(13) },
  { id: 's10', businessId: 'b6', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Porch Refresh & Repair', description: 'Board replacement, railing tightening, and a fresh coat of paint or stain.', category: 'Deck or Porch', standardPrice: 297, discountPercentage: 12, requiredSignups: 4, currentSignups: 3, signedUpUserIds: genSignupIds(3), expiresAt: daysFromNow(7) },
  { id: 's11', businessId: 'b6', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Deck Staining & Sealing', description: 'Pressure wash, sand, and reseal your deck to protect it through another Carolina summer.', category: 'Deck or Porch', standardPrice: 232, discountPercentage: 13, requiredSignups: 4, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(21) },
  { id: 's12', businessId: 'b6', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Deck Inspection & Tune-Up', description: 'A structural check plus minor repairs to keep your deck safe for the season.', category: 'Deck or Porch', standardPrice: 322, discountPercentage: 20, requiredSignups: 5, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(12) },
  { id: 's13', businessId: 'b7', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Whole-Home Electrical Safety Inspection', description: 'A licensed electrician checks panels, outlets, and wiring for safety issues.', category: 'Electrical', standardPrice: 376, discountPercentage: 18, requiredSignups: 7, currentSignups: 7, signedUpUserIds: genSignupIds(7), expiresAt: daysFromNow(19) },
  { id: 's14', businessId: 'b7', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Outdoor & Landscape Lighting Install', description: 'Low-voltage lighting installed along walkways, decks, and garden beds.', category: 'Electrical', standardPrice: 267, discountPercentage: 19, requiredSignups: 12, currentSignups: 2, signedUpUserIds: genSignupIds(2), expiresAt: daysFromNow(13) },
  { id: 's15', businessId: 'b7', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Ceiling Fan & Fixture Installation', description: 'Swap out dated fixtures or add new ceiling fans, wired safely to code.', category: 'Electrical', standardPrice: 346, discountPercentage: 12, requiredSignups: 7, currentSignups: 6, signedUpUserIds: genSignupIds(6), expiresAt: daysFromNow(11) },
  { id: 's16', businessId: 'b7', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Surge Protection Upgrade', description: 'Whole-panel surge protection to guard electronics from summer storm surges.', category: 'Electrical', standardPrice: 361, discountPercentage: 19, requiredSignups: 10, currentSignups: 0, signedUpUserIds: genSignupIds(0), expiresAt: daysFromNow(2) },
  { id: 's17', businessId: 'b8', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Fence Staining & Weatherproofing', description: 'Clean and reseal wood fencing to resist rot and sun damage.', category: 'Fencing Service', standardPrice: 485, discountPercentage: 20, requiredSignups: 11, currentSignups: 8, signedUpUserIds: genSignupIds(8), expiresAt: daysFromNow(4) },
  { id: 's18', businessId: 'b8', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Fence Repair & Panel Replacement', description: 'Fix leaning posts and swap damaged panels to keep your fence line solid.', category: 'Fencing Service', standardPrice: 294, discountPercentage: 11, requiredSignups: 4, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(10) },
  { id: 's19', businessId: 'b8', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'New Privacy Fence Installation', description: 'A full privacy fence section installed and leveled by a licensed crew.', category: 'Fencing Service', standardPrice: 419, discountPercentage: 17, requiredSignups: 11, currentSignups: 2, signedUpUserIds: genSignupIds(2), expiresAt: daysFromNow(14) },
  { id: 's20', businessId: 'b8', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Gate Hardware Tune-Up', description: 'Realign gates and replace worn hinges and latches.', category: 'Fencing Service', standardPrice: 397, discountPercentage: 14, requiredSignups: 8, currentSignups: 3, signedUpUserIds: genSignupIds(3), expiresAt: daysFromNow(7) },
  { id: 's21', businessId: 'b9', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Downspout Repair & Realignment', description: 'Fix disconnected or misaligned downspouts causing water pooling near your foundation.', category: 'Gutter Cleaning', standardPrice: 143, discountPercentage: 14, requiredSignups: 4, currentSignups: 0, signedUpUserIds: genSignupIds(0), expiresAt: daysFromNow(2) },
  { id: 's22', businessId: 'b9', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Storm Debris Cleanup', description: 'Post-storm gutter and roof-edge debris clearing.', category: 'Gutter Cleaning', standardPrice: 111, discountPercentage: 21, requiredSignups: 10, currentSignups: 9, signedUpUserIds: genSignupIds(9), expiresAt: daysFromNow(1) },
  { id: 's23', businessId: 'b9', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Gutter Guard Installation', description: 'Mesh guards installed to cut down on future clogging from falling leaves and pine needles.', category: 'Gutter Cleaning', standardPrice: 128, discountPercentage: 16, requiredSignups: 6, currentSignups: 3, signedUpUserIds: genSignupIds(3), expiresAt: daysFromNow(5) },
  { id: 's24', businessId: 'b9', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Full Gutter Cleaning & Flush', description: 'Clear debris and flush downspouts so summer storms drain properly.', category: 'Gutter Cleaning', standardPrice: 194, discountPercentage: 25, requiredSignups: 6, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(20) },
  { id: 's25', businessId: 'b10', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Drywall Patch & Paint Touch-Up', description: 'Repair dings, holes, and scuffs with a seamless paint match.', category: 'Handyman Service', standardPrice: 212, discountPercentage: 12, requiredSignups: 11, currentSignups: 6, signedUpUserIds: genSignupIds(6), expiresAt: daysFromNow(10) },
  { id: 's26', businessId: 'b10', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Furniture Assembly & Mounting', description: 'TV mounting, shelving, and flat-pack furniture assembly.', category: 'Handyman Service', standardPrice: 102, discountPercentage: 15, requiredSignups: 12, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(10) },
  { id: 's27', businessId: 'b10', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Door & Window Adjustment', description: 'Fix sticking doors, drafty windows, and misaligned frames.', category: 'Handyman Service', standardPrice: 195, discountPercentage: 17, requiredSignups: 8, currentSignups: 0, signedUpUserIds: genSignupIds(0), expiresAt: daysFromNow(4) },
  { id: 's28', businessId: 'b10', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Honey-Do List Bundle', description: 'A half-day handyman visit to knock out your backlog of small repairs.', category: 'Handyman Service', standardPrice: 106, discountPercentage: 11, requiredSignups: 7, currentSignups: 6, signedUpUserIds: genSignupIds(6), expiresAt: daysFromNow(15) },
  { id: 's29', businessId: 'b11', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Smart Doorbell Camera Install', description: 'Professional install and setup of a video doorbell with app configuration.', category: 'Home Security', standardPrice: 190, discountPercentage: 10, requiredSignups: 4, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(6) },
  { id: 's30', businessId: 'b11', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Home Security Assessment', description: 'A walkthrough audit identifying vulnerable entry points and blind spots.', category: 'Home Security', standardPrice: 230, discountPercentage: 20, requiredSignups: 9, currentSignups: 3, signedUpUserIds: genSignupIds(3), expiresAt: daysFromNow(14) },
  { id: 's31', businessId: 'b11', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Smart Lock Upgrade', description: 'Keyless smart lock installation on your front and back doors.', category: 'Home Security', standardPrice: 161, discountPercentage: 18, requiredSignups: 11, currentSignups: 3, signedUpUserIds: genSignupIds(3), expiresAt: daysFromNow(17) },
  { id: 's32', businessId: 'b11', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Whole-Home Camera System', description: 'Multi-camera exterior security system install with mobile monitoring.', category: 'Home Security', standardPrice: 327, discountPercentage: 11, requiredSignups: 4, currentSignups: 2, signedUpUserIds: genSignupIds(2), expiresAt: daysFromNow(19) },
  { id: 's33', businessId: 'b3', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Deep House Cleaning', description: 'A one-time, top-to-bottom deep clean of your entire home. Perfect for spring cleaning or special occasions.', category: 'House Cleaning', standardPrice: 212, discountPercentage: 20, requiredSignups: 5, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(8) },
  { id: 's34', businessId: 'b3', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Move-In Deep Clean', description: 'A thorough top-to-bottom clean, perfect for new homeowners settling in.', category: 'House Cleaning', standardPrice: 153, discountPercentage: 18, requiredSignups: 10, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(6) },
  { id: 's35', businessId: 'b3', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Seasonal Refresh Cleaning', description: 'A seasonal detail clean covering windowsills, vents, and baseboards.', category: 'House Cleaning', standardPrice: 215, discountPercentage: 10, requiredSignups: 11, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(6) },
  { id: 's36', businessId: 'b3', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Standard Weekly Cleaning', description: 'Consistent weekly upkeep covering kitchens, bathrooms, and common areas.', category: 'House Cleaning', standardPrice: 216, discountPercentage: 10, requiredSignups: 9, currentSignups: 0, signedUpUserIds: genSignupIds(0), expiresAt: daysFromNow(19) },
  { id: 's37', businessId: 'b12', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Move-In Deep Clean', description: 'A thorough top-to-bottom clean, perfect for new homeowners settling in.', category: 'House Cleaning', standardPrice: 238, discountPercentage: 23, requiredSignups: 9, currentSignups: 8, signedUpUserIds: genSignupIds(8), expiresAt: daysFromNow(21) },
  { id: 's38', businessId: 'b12', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Standard Weekly Cleaning', description: 'Consistent weekly upkeep covering kitchens, bathrooms, and common areas.', category: 'House Cleaning', standardPrice: 281, discountPercentage: 25, requiredSignups: 11, currentSignups: 11, signedUpUserIds: genSignupIds(11), expiresAt: daysFromNow(2) },
  { id: 's39', businessId: 'b12', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Seasonal Refresh Cleaning', description: 'A seasonal detail clean covering windowsills, vents, and baseboards.', category: 'House Cleaning', standardPrice: 319, discountPercentage: 10, requiredSignups: 8, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(17) },
  { id: 's40', businessId: 'b12', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Deep House Cleaning', description: 'A one-time, top-to-bottom deep clean of your entire home. Perfect for spring cleaning or special occasions.', category: 'House Cleaning', standardPrice: 179, discountPercentage: 23, requiredSignups: 8, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(6) },
  { id: 's41', businessId: 'b13', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Duct Cleaning & Inspection', description: 'Clear dust and debris from ductwork to improve airflow and air quality.', category: 'HVAC Maintenance', standardPrice: 178, discountPercentage: 19, requiredSignups: 12, currentSignups: 12, signedUpUserIds: genSignupIds(12), expiresAt: daysFromNow(13) },
  { id: 's42', businessId: 'b13', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Thermostat Upgrade Install', description: 'Smart thermostat installation and setup for better temperature control.', category: 'HVAC Maintenance', standardPrice: 104, discountPercentage: 21, requiredSignups: 11, currentSignups: 6, signedUpUserIds: genSignupIds(6), expiresAt: daysFromNow(18) },
  { id: 's43', businessId: 'b13', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Filter Replacement Plan', description: 'Quarterly filter swaps to keep your system running efficiently year-round.', category: 'HVAC Maintenance', standardPrice: 164, discountPercentage: 20, requiredSignups: 5, currentSignups: 1, signedUpUserIds: genSignupIds(1), expiresAt: daysFromNow(15) },
  { id: 's44', businessId: 'b13', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'AC Summer Tune-Up', description: 'A full inspection and tune-up to keep your AC running efficiently through peak summer heat.', category: 'HVAC Maintenance', standardPrice: 225, discountPercentage: 19, requiredSignups: 8, currentSignups: 7, signedUpUserIds: genSignupIds(7), expiresAt: daysFromNow(17) },
  { id: 's45', businessId: 'b14', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Home Staging Consultation', description: 'Staging advice to help your home show its best for sale or photos.', category: 'Interior Design', standardPrice: 214, discountPercentage: 16, requiredSignups: 5, currentSignups: 0, signedUpUserIds: genSignupIds(0), expiresAt: daysFromNow(15) },
  { id: 's46', businessId: 'b14', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Color Consultation & Paint Plan', description: 'Professional color palette guidance for your whole home or a single space.', category: 'Interior Design', standardPrice: 289, discountPercentage: 13, requiredSignups: 12, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(13) },
  { id: 's47', businessId: 'b14', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Single-Room Design Consultation', description: 'An in-home consult with a mood board and furniture layout plan for one room.', category: 'Interior Design', standardPrice: 198, discountPercentage: 17, requiredSignups: 12, currentSignups: 8, signedUpUserIds: genSignupIds(8), expiresAt: daysFromNow(8) },
  { id: 's48', businessId: 'b14', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Closet & Storage Redesign', description: 'A functional redesign to maximize closet and storage space.', category: 'Interior Design', standardPrice: 330, discountPercentage: 15, requiredSignups: 12, currentSignups: 12, signedUpUserIds: genSignupIds(12), expiresAt: daysFromNow(4) },
  { id: 's49', businessId: 'b15', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Landscape Design Consultation', description: 'A full-yard design plan tailored to your home\'s style and sun exposure.', category: 'Landscaping', standardPrice: 360, discountPercentage: 14, requiredSignups: 9, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(14) },
  { id: 's50', businessId: 'b15', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Seasonal Flower Bed Planting', description: 'Planting of seasonal color beds chosen for Wake County\'s climate.', category: 'Landscaping', standardPrice: 295, discountPercentage: 14, requiredSignups: 5, currentSignups: 0, signedUpUserIds: genSignupIds(0), expiresAt: daysFromNow(15) },
  { id: 's51', businessId: 'b15', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Shrub & Hedge Trimming', description: 'Shaping and trimming of shrubs, hedges, and small ornamental trees.', category: 'Landscaping', standardPrice: 227, discountPercentage: 13, requiredSignups: 4, currentSignups: 0, signedUpUserIds: genSignupIds(0), expiresAt: daysFromNow(14) },
  { id: 's52', businessId: 'b15', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Mulching & Bed Refresh', description: 'Fresh mulch and bed edging to make your landscaping pop.', category: 'Landscaping', standardPrice: 198, discountPercentage: 10, requiredSignups: 8, currentSignups: 1, signedUpUserIds: genSignupIds(1), expiresAt: daysFromNow(15) },
  { id: 's53', businessId: 'b2', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Weed Control & Fertilization', description: 'A seasonal treatment plan to control weeds and green up your lawn.', category: 'Lawn Service', standardPrice: 205, discountPercentage: 16, requiredSignups: 5, currentSignups: 0, signedUpUserIds: genSignupIds(0), expiresAt: daysFromNow(19) },
  { id: 's54', businessId: 'b2', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Weekly Mowing Plan', description: 'Consistent weekly mowing and edging through the growing season.', category: 'Lawn Service', standardPrice: 75, discountPercentage: 15, requiredSignups: 8, currentSignups: 7, signedUpUserIds: genSignupIds(7), expiresAt: daysFromNow(12) },
  { id: 's55', businessId: 'b2', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Full-Service Lawn Care', description: 'Mowing, edging, and blowing services to maintain a pristine lawn. Includes fertilization twice a season.', category: 'Lawn Service', standardPrice: 168, discountPercentage: 15, requiredSignups: 12, currentSignups: 1, signedUpUserIds: genSignupIds(1), expiresAt: daysFromNow(5) },
  { id: 's56', businessId: 'b2', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Aeration & Overseeding', description: 'Core aeration and overseeding to thicken up thin or patchy lawns.', category: 'Lawn Service', standardPrice: 208, discountPercentage: 14, requiredSignups: 10, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(7) },
  { id: 's57', businessId: 'b16', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Packing & Unpacking Service', description: 'Full packing service with quality materials, plus unpacking at your new home.', category: 'Moving Services', standardPrice: 413, discountPercentage: 12, requiredSignups: 5, currentSignups: 2, signedUpUserIds: genSignupIds(2), expiresAt: daysFromNow(3) },
  { id: 's58', businessId: 'b16', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Single-Item Furniture Delivery', description: 'Safe transport and placement for a couch, mattress, or large appliance.', category: 'Moving Services', standardPrice: 577, discountPercentage: 10, requiredSignups: 10, currentSignups: 1, signedUpUserIds: genSignupIds(1), expiresAt: daysFromNow(14) },
  { id: 's59', businessId: 'b16', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Storage Unit Loading Help', description: 'Two movers to help load or unload a storage unit efficiently.', category: 'Moving Services', standardPrice: 545, discountPercentage: 12, requiredSignups: 11, currentSignups: 11, signedUpUserIds: genSignupIds(11), expiresAt: daysFromNow(21) },
  { id: 's60', businessId: 'b16', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Local Move - 2 Movers & Truck', description: 'A local move within Wake County with two movers and a truck for up to 4 hours.', category: 'Moving Services', standardPrice: 353, discountPercentage: 14, requiredSignups: 4, currentSignups: 1, signedUpUserIds: genSignupIds(1), expiresAt: daysFromNow(9) },
  { id: 's61', businessId: 'b17', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Cabinet Refinishing', description: 'Sand, prime, and repaint kitchen or bathroom cabinets for a like-new look.', category: 'Painting', standardPrice: 538, discountPercentage: 18, requiredSignups: 4, currentSignups: 1, signedUpUserIds: genSignupIds(1), expiresAt: daysFromNow(12) },
  { id: 's62', businessId: 'b17', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Exterior Trim & Shutter Painting', description: 'Refresh faded trim, shutters, and doors with weather-resistant paint.', category: 'Painting', standardPrice: 372, discountPercentage: 10, requiredSignups: 6, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(12) },
  { id: 's63', businessId: 'b17', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Interior Room Repaint', description: 'Two-coat professional repaint for a single room, prep and cleanup included.', category: 'Painting', standardPrice: 287, discountPercentage: 10, requiredSignups: 11, currentSignups: 0, signedUpUserIds: genSignupIds(0), expiresAt: daysFromNow(20) },
  { id: 's64', businessId: 'b17', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Whole-House Interior Painting', description: 'A full interior repaint across main living spaces.', category: 'Painting', standardPrice: 355, discountPercentage: 20, requiredSignups: 12, currentSignups: 2, signedUpUserIds: genSignupIds(2), expiresAt: daysFromNow(8) },
  { id: 's65', businessId: 'b18', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Termite Inspection', description: 'A full termite inspection with a written report, recommended before closing on a home.', category: 'Pest Control', standardPrice: 167, discountPercentage: 24, requiredSignups: 11, currentSignups: 8, signedUpUserIds: genSignupIds(8), expiresAt: daysFromNow(4) },
  { id: 's66', businessId: 'b18', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Quarterly Pest Prevention Plan', description: 'Ongoing exterior treatment to keep ants, spiders, and roaches out year-round.', category: 'Pest Control', standardPrice: 139, discountPercentage: 21, requiredSignups: 7, currentSignups: 7, signedUpUserIds: genSignupIds(7), expiresAt: daysFromNow(21) },
  { id: 's67', businessId: 'b18', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'One-Time Ant & Roach Treatment', description: 'Targeted indoor and outdoor treatment for an active ant or roach problem.', category: 'Pest Control', standardPrice: 209, discountPercentage: 18, requiredSignups: 12, currentSignups: 2, signedUpUserIds: genSignupIds(2), expiresAt: daysFromNow(11) },
  { id: 's68', businessId: 'b18', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Mosquito Yard Treatment', description: 'Barrier spray treatment to cut down on mosquitoes for summer evenings outside.', category: 'Pest Control', standardPrice: 200, discountPercentage: 15, requiredSignups: 8, currentSignups: 3, signedUpUserIds: genSignupIds(3), expiresAt: daysFromNow(16) },
  { id: 's69', businessId: 'b19', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Fixture Upgrade Install', description: 'Install new faucets, showerheads, or toilets with old fixture removal.', category: 'Plumbing', standardPrice: 167, discountPercentage: 16, requiredSignups: 12, currentSignups: 12, signedUpUserIds: genSignupIds(12), expiresAt: daysFromNow(9) },
  { id: 's70', businessId: 'b19', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Drain Clearing Service', description: 'Clear slow or clogged drains in kitchens and bathrooms.', category: 'Plumbing', standardPrice: 176, discountPercentage: 13, requiredSignups: 10, currentSignups: 2, signedUpUserIds: genSignupIds(2), expiresAt: daysFromNow(14) },
  { id: 's71', businessId: 'b19', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Water Heater Flush & Inspection', description: 'Flush sediment and inspect your water heater to extend its lifespan.', category: 'Plumbing', standardPrice: 256, discountPercentage: 16, requiredSignups: 12, currentSignups: 10, signedUpUserIds: genSignupIds(10), expiresAt: daysFromNow(13) },
  { id: 's72', businessId: 'b19', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Whole-Home Plumbing Inspection', description: 'A licensed plumber checks supply lines, drains, and fixtures for leaks and wear.', category: 'Plumbing', standardPrice: 197, discountPercentage: 14, requiredSignups: 11, currentSignups: 11, signedUpUserIds: genSignupIds(11), expiresAt: daysFromNow(2) },
  { id: 's73', businessId: 'b1', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Green Pool Recovery', description: 'Shock treatment and filtration to bring a green or cloudy pool back to crystal clear.', category: 'Pool Maintenance', standardPrice: 108, discountPercentage: 24, requiredSignups: 10, currentSignups: 3, signedUpUserIds: genSignupIds(3), expiresAt: daysFromNow(3) },
  { id: 's74', businessId: 'b1', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Pool Opening Service', description: 'Get your pool ready for summer with our professional pool opening service. We handle everything!', category: 'Pool Maintenance', standardPrice: 267, discountPercentage: 16, requiredSignups: 9, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(8) },
  { id: 's75', businessId: 'b1', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Pool Closing & Winterization', description: 'Professional pool winterization to protect your investment through the off-season.', category: 'Pool Maintenance', standardPrice: 202, discountPercentage: 10, requiredSignups: 6, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(12) },
  { id: 's76', businessId: 'b1', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Scheduled Pool Maintenance', description: 'Weekly cleaning, chemical balancing, and equipment checks to keep your pool sparkling clean all season long.', category: 'Pool Maintenance', standardPrice: 202, discountPercentage: 13, requiredSignups: 4, currentSignups: 1, signedUpUserIds: genSignupIds(1), expiresAt: daysFromNow(7) },
  { id: 's77', businessId: 'b20', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Deck & Patio Power Wash', description: 'Deep clean for decks and patios ahead of staining or summer entertaining.', category: 'Power Washing', standardPrice: 276, discountPercentage: 14, requiredSignups: 4, currentSignups: 3, signedUpUserIds: genSignupIds(3), expiresAt: daysFromNow(11) },
  { id: 's78', businessId: 'b20', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Driveway & Walkway Cleaning', description: 'High-pressure cleaning to lift oil stains and built-up dirt from concrete.', category: 'Power Washing', standardPrice: 105, discountPercentage: 15, requiredSignups: 6, currentSignups: 3, signedUpUserIds: genSignupIds(3), expiresAt: daysFromNow(3) },
  { id: 's79', businessId: 'b20', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Roof Soft Wash', description: 'A low-pressure soft wash to remove algae streaks without damaging shingles.', category: 'Power Washing', standardPrice: 144, discountPercentage: 20, requiredSignups: 10, currentSignups: 9, signedUpUserIds: genSignupIds(9), expiresAt: daysFromNow(11) },
  { id: 's80', businessId: 'b20', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'House Exterior Power Wash', description: 'Full siding wash to remove pollen, mildew, and grime from your home\'s exterior.', category: 'Power Washing', standardPrice: 253, discountPercentage: 24, requiredSignups: 10, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(5) },
  { id: 's81', businessId: 'b21', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Storm Damage Assessment', description: 'A post-storm inspection to document damage for insurance claims.', category: 'Roofing', standardPrice: 276, discountPercentage: 10, requiredSignups: 7, currentSignups: 7, signedUpUserIds: genSignupIds(7), expiresAt: daysFromNow(16) },
  { id: 's82', businessId: 'b21', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Minor Roof Repair', description: 'Patch small leaks, replace damaged shingles, and reseal flashing.', category: 'Roofing', standardPrice: 178, discountPercentage: 17, requiredSignups: 5, currentSignups: 2, signedUpUserIds: genSignupIds(2), expiresAt: daysFromNow(1) },
  { id: 's83', businessId: 'b21', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Roof Moss & Algae Treatment', description: 'Treatment to remove and prevent moss and algae streaking on shingles.', category: 'Roofing', standardPrice: 161, discountPercentage: 12, requiredSignups: 12, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(7) },
  { id: 's84', businessId: 'b21', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Roof Inspection & Report', description: 'A full roof inspection with photos and a written condition report.', category: 'Roofing', standardPrice: 372, discountPercentage: 18, requiredSignups: 6, currentSignups: 6, signedUpUserIds: genSignupIds(6), expiresAt: daysFromNow(4) },
  { id: 's89', businessId: 'b23', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Panel Mounting Hardware Inspection', description: 'A safety check of mounting hardware and roof penetrations.', category: 'Solar Panel Installation', standardPrice: 239, discountPercentage: 16, requiredSignups: 7, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(6) },
  { id: 's90', businessId: 'b23', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Solar Panel Cleaning & Inspection', description: 'Cleaning and performance inspection to keep your panels running at peak output.', category: 'Solar Panel Installation', standardPrice: 233, discountPercentage: 12, requiredSignups: 7, currentSignups: 1, signedUpUserIds: genSignupIds(1), expiresAt: daysFromNow(11) },
  { id: 's91', businessId: 'b23', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Solar Consultation & Site Assessment', description: 'An on-site assessment of your roof\'s solar potential and estimated savings.', category: 'Solar Panel Installation', standardPrice: 197, discountPercentage: 12, requiredSignups: 7, currentSignups: 7, signedUpUserIds: genSignupIds(7), expiresAt: daysFromNow(6) },
  { id: 's92', businessId: 'b23', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Solar System Health Check', description: 'A technician checks inverters, wiring, and output against expected performance.', category: 'Solar Panel Installation', standardPrice: 300, discountPercentage: 10, requiredSignups: 7, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(10) },
  { id: 's93', businessId: 'b24', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Stump Grinding', description: 'Grinding out old stumps so you can reclaim the yard space.', category: 'Tree Service', standardPrice: 470, discountPercentage: 17, requiredSignups: 8, currentSignups: 3, signedUpUserIds: genSignupIds(3), expiresAt: daysFromNow(13) },
  { id: 's94', businessId: 'b24', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Tree Trimming & Pruning', description: 'Professional pruning to improve tree health and reduce storm-damage risk.', category: 'Tree Service', standardPrice: 456, discountPercentage: 13, requiredSignups: 7, currentSignups: 6, signedUpUserIds: genSignupIds(6), expiresAt: daysFromNow(16) },
  { id: 's95', businessId: 'b24', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Tree Removal', description: 'Safe removal of a dead or hazardous tree, including debris haul-away.', category: 'Tree Service', standardPrice: 154, discountPercentage: 15, requiredSignups: 12, currentSignups: 12, signedUpUserIds: genSignupIds(12), expiresAt: daysFromNow(3) },
  { id: 's96', businessId: 'b24', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Storm Damage Tree Cleanup', description: 'Fast cleanup and hauling after storm-damaged limbs and trees.', category: 'Tree Service', standardPrice: 169, discountPercentage: 14, requiredSignups: 6, currentSignups: 5, signedUpUserIds: genSignupIds(5), expiresAt: daysFromNow(13) },
  { id: 's97', businessId: 'b25', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Screen Cleaning & Repair', description: 'Screen cleaning with repair or replacement for torn screens.', category: 'Window Washing', standardPrice: 204, discountPercentage: 12, requiredSignups: 4, currentSignups: 0, signedUpUserIds: genSignupIds(0), expiresAt: daysFromNow(7) },
  { id: 's98', businessId: 'b25', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Interior & Exterior Window Cleaning', description: 'A full streak-free clean for every window, inside and out.', category: 'Window Washing', standardPrice: 158, discountPercentage: 18, requiredSignups: 4, currentSignups: 3, signedUpUserIds: genSignupIds(3), expiresAt: daysFromNow(11) },
  { id: 's99', businessId: 'b25', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Gutter & Window Combo Clean', description: 'Bundled gutter clearing and window washing in one visit.', category: 'Window Washing', standardPrice: 155, discountPercentage: 17, requiredSignups: 4, currentSignups: 2, signedUpUserIds: genSignupIds(2), expiresAt: daysFromNow(2) },
  { id: 's100', businessId: 'b25', neighborhoodIds: [DEMO_NEIGHBORHOOD_IDS[0]], title: 'Post-Construction Window Clean', description: 'Removal of dust, stickers, and residue after a renovation project.', category: 'Window Washing', standardPrice: 105, discountPercentage: 13, requiredSignups: 4, currentSignups: 4, signedUpUserIds: genSignupIds(4), expiresAt: daysFromNow(16) },
];

// ==== GENERATED REVIEWS (auto-generated) ====
const GENERATED_REVIEWS: Review[] = [
  { id: 'r1', businessId: 'b4', userId: 'rev-b4-0', userName: 'Hannah K.', rating: 5, text: 'Triangle Carpet Care did an incredible job — on time, professional, and the results speak for themselves. Highly recommend to any neighbor.', date: daysFromNow(-40), isVerifiedNeighbor: false },
  { id: 'r2', businessId: 'b4', userId: 'rev-b4-1', userName: 'Sarah B.', rating: 5, text: 'We\'ve used Triangle Carpet Care twice now and both times were flawless. They clearly care about doing the job right.', date: daysFromNow(-12), isVerifiedNeighbor: true },
  { id: 'r3', businessId: 'b4', userId: 'rev-b4-2', userName: 'Laura C.', rating: 5, text: 'Fast, friendly, and thorough. Triangle Carpet Care is now our go-to for anything in this category.', date: daysFromNow(-48), isVerifiedNeighbor: false },
  { id: 'r4', businessId: 'b4', userId: 'rev-b4-3', userName: 'James L.', rating: 5, text: 'Best carpet cleaning experience we\'ve had in the neighborhood. Fair pricing and great communication the whole way through.', date: daysFromNow(-63), isVerifiedNeighbor: false },
  { id: 'r5', businessId: 'b4', userId: 'rev-b4-4', userName: 'David F.', rating: 4, text: 'Happy with the results. Would use Triangle Carpet Care again for future projects.', date: daysFromNow(-196), isVerifiedNeighbor: true },
  { id: 'r6', businessId: 'b4', userId: 'rev-b4-5', userName: 'Mark M.', rating: 3, text: 'Decent job from Triangle Carpet Care, but there were a couple of things that needed a follow-up visit.', date: daysFromNow(-27), isVerifiedNeighbor: true },
  { id: 'r7', businessId: 'b5', userId: 'rev-b5-0', userName: 'Erin N.', rating: 5, text: 'Fast, friendly, and thorough. Tidy Triangle Maids is now our go-to for anything in this category.', date: daysFromNow(-69), isVerifiedNeighbor: true },
  { id: 'r8', businessId: 'b5', userId: 'rev-b5-1', userName: 'Christine W.', rating: 5, text: 'Exceeded expectations. The crew was respectful of our property and cleaned up after themselves.', date: daysFromNow(-31), isVerifiedNeighbor: false },
  { id: 'r9', businessId: 'b5', userId: 'rev-b5-2', userName: 'John H.', rating: 4, text: 'Solid work overall from Tidy Triangle Maids. A little pricier than expected but the quality was there.', date: daysFromNow(-90), isVerifiedNeighbor: true },
  { id: 'r10', businessId: 'b5', userId: 'rev-b5-3', userName: 'Laura C.', rating: 5, text: 'Fast, friendly, and thorough. Tidy Triangle Maids is now our go-to for anything in this category.', date: daysFromNow(-187), isVerifiedNeighbor: true },
  { id: 'r11', businessId: 'b6', userId: 'rev-b6-0', userName: 'Dan M.', rating: 5, text: 'We\'ve used Wake Deck Builders twice now and both times were flawless. They clearly care about doing the job right.', date: daysFromNow(-91), isVerifiedNeighbor: true },
  { id: 'r12', businessId: 'b6', userId: 'rev-b6-1', userName: 'Mike B.', rating: 4, text: 'Good experience with Wake Deck Builders, though scheduling took a bit longer than I\'d hoped.', date: daysFromNow(-107), isVerifiedNeighbor: true },
  { id: 'r13', businessId: 'b6', userId: 'rev-b6-2', userName: 'Laura P.', rating: 5, text: 'Best deck or porch experience we\'ve had in the neighborhood. Fair pricing and great communication the whole way through.', date: daysFromNow(-66), isVerifiedNeighbor: true },
  { id: 'r14', businessId: 'b6', userId: 'rev-b6-3', userName: 'Emily D.', rating: 5, text: 'Fast, friendly, and thorough. Wake Deck Builders is now our go-to for anything in this category.', date: daysFromNow(-69), isVerifiedNeighbor: true },
  { id: 'r15', businessId: 'b7', userId: 'rev-b7-0', userName: 'Christine G.', rating: 5, text: 'Fast, friendly, and thorough. BrightSpark Electric is now our go-to for anything in this category.', date: daysFromNow(-161), isVerifiedNeighbor: true },
  { id: 'r16', businessId: 'b7', userId: 'rev-b7-1', userName: 'Kevin S.', rating: 4, text: 'Professional and got the job done. A few small things could\'ve been communicated better.', date: daysFromNow(-128), isVerifiedNeighbor: false },
  { id: 'r17', businessId: 'b7', userId: 'rev-b7-2', userName: 'Mike D.', rating: 4, text: 'Good experience with BrightSpark Electric, though scheduling took a bit longer than I\'d hoped.', date: daysFromNow(-198), isVerifiedNeighbor: false },
  { id: 'r18', businessId: 'b8', userId: 'rev-b8-0', userName: 'Amanda B.', rating: 5, text: 'We\'ve used SecureLine Fencing twice now and both times were flawless. They clearly care about doing the job right.', date: daysFromNow(-60), isVerifiedNeighbor: true },
  { id: 'r19', businessId: 'b8', userId: 'rev-b8-1', userName: 'John F.', rating: 5, text: 'SecureLine Fencing did an incredible job — on time, professional, and the results speak for themselves. Highly recommend to any neighbor.', date: daysFromNow(-5), isVerifiedNeighbor: true },
  { id: 'r20', businessId: 'b8', userId: 'rev-b8-2', userName: 'David G.', rating: 4, text: 'Good experience with SecureLine Fencing, though scheduling took a bit longer than I\'d hoped.', date: daysFromNow(-108), isVerifiedNeighbor: true },
  { id: 'r21', businessId: 'b8', userId: 'rev-b8-3', userName: 'Tom L.', rating: 5, text: 'Best fencing service experience we\'ve had in the neighborhood. Fair pricing and great communication the whole way through.', date: daysFromNow(-149), isVerifiedNeighbor: false },
  { id: 'r22', businessId: 'b9', userId: 'rev-b9-0', userName: 'Steve C.', rating: 4, text: 'Professional and got the job done. A few small things could\'ve been communicated better.', date: daysFromNow(-69), isVerifiedNeighbor: true },
  { id: 'r23', businessId: 'b9', userId: 'rev-b9-1', userName: 'Christine F.', rating: 4, text: 'Happy with the results. Would use ClearFlow Gutters again for future projects.', date: daysFromNow(-117), isVerifiedNeighbor: false },
  { id: 'r24', businessId: 'b9', userId: 'rev-b9-2', userName: 'Hannah M.', rating: 5, text: 'Fast, friendly, and thorough. ClearFlow Gutters is now our go-to for anything in this category.', date: daysFromNow(-142), isVerifiedNeighbor: false },
  { id: 'r25', businessId: 'b9', userId: 'rev-b9-3', userName: 'Kevin K.', rating: 5, text: 'Exceeded expectations. The crew was respectful of our property and cleaned up after themselves.', date: daysFromNow(-90), isVerifiedNeighbor: false },
  { id: 'r26', businessId: 'b9', userId: 'rev-b9-4', userName: 'John D.', rating: 4, text: 'Professional and got the job done. A few small things could\'ve been communicated better.', date: daysFromNow(-147), isVerifiedNeighbor: false },
  { id: 'r27', businessId: 'b10', userId: 'rev-b10-0', userName: 'James G.', rating: 5, text: 'Best handyman service experience we\'ve had in the neighborhood. Fair pricing and great communication the whole way through.', date: daysFromNow(-149), isVerifiedNeighbor: true },
  { id: 'r28', businessId: 'b10', userId: 'rev-b10-1', userName: 'David H.', rating: 3, text: 'It was okay — got the job done but not quite the wow factor I was expecting.', date: daysFromNow(-76), isVerifiedNeighbor: true },
  { id: 'r29', businessId: 'b10', userId: 'rev-b10-2', userName: 'Lisa K.', rating: 5, text: 'Best handyman service experience we\'ve had in the neighborhood. Fair pricing and great communication the whole way through.', date: daysFromNow(-58), isVerifiedNeighbor: true },
  { id: 'r30', businessId: 'b11', userId: 'rev-b11-0', userName: 'John B.', rating: 5, text: 'Exceeded expectations. The crew was respectful of our property and cleaned up after themselves.', date: daysFromNow(-41), isVerifiedNeighbor: false },
  { id: 'r31', businessId: 'b11', userId: 'rev-b11-1', userName: 'John H.', rating: 5, text: 'Fast, friendly, and thorough. GuardPost Security is now our go-to for anything in this category.', date: daysFromNow(-54), isVerifiedNeighbor: true },
  { id: 'r32', businessId: 'b11', userId: 'rev-b11-2', userName: 'Amanda C.', rating: 4, text: 'Solid work overall from GuardPost Security. A little pricier than expected but the quality was there.', date: daysFromNow(-194), isVerifiedNeighbor: true },
  { id: 'r33', businessId: 'b11', userId: 'rev-b11-3', userName: 'Sarah D.', rating: 3, text: 'It was okay — got the job done but not quite the wow factor I was expecting.', date: daysFromNow(-63), isVerifiedNeighbor: false },
  { id: 'r34', businessId: 'b11', userId: 'rev-b11-4', userName: 'Nicole W.', rating: 4, text: 'Good experience with GuardPost Security, though scheduling took a bit longer than I\'d hoped.', date: daysFromNow(-182), isVerifiedNeighbor: true },
  { id: 'r35', businessId: 'b11', userId: 'rev-b11-5', userName: 'David W.', rating: 5, text: 'GuardPost Security did an incredible job — on time, professional, and the results speak for themselves. Highly recommend to any neighbor.', date: daysFromNow(-180), isVerifiedNeighbor: false },
  { id: 'r36', businessId: 'b3', userId: 'rev-b3-0', userName: 'Jessica B.', rating: 4, text: 'Professional and got the job done. A few small things could\'ve been communicated better.', date: daysFromNow(-16), isVerifiedNeighbor: true },
  { id: 'r37', businessId: 'b3', userId: 'rev-b3-1', userName: 'Jessica T.', rating: 5, text: 'We\'ve used SparkleClean Homes twice now and both times were flawless. They clearly care about doing the job right.', date: daysFromNow(-97), isVerifiedNeighbor: false },
  { id: 'r38', businessId: 'b3', userId: 'rev-b3-2', userName: 'Rachel P.', rating: 5, text: 'Fast, friendly, and thorough. SparkleClean Homes is now our go-to for anything in this category.', date: daysFromNow(-42), isVerifiedNeighbor: false },
  { id: 'r39', businessId: 'b3', userId: 'rev-b3-3', userName: 'Nicole T.', rating: 5, text: 'Fast, friendly, and thorough. SparkleClean Homes is now our go-to for anything in this category.', date: daysFromNow(-190), isVerifiedNeighbor: true },
  { id: 'r40', businessId: 'b3', userId: 'rev-b3-4', userName: 'Paul L.', rating: 5, text: 'We\'ve used SparkleClean Homes twice now and both times were flawless. They clearly care about doing the job right.', date: daysFromNow(-101), isVerifiedNeighbor: false },
  { id: 'r41', businessId: 'b3', userId: 'rev-b3-5', userName: 'Steve T.', rating: 4, text: 'Professional and got the job done. A few small things could\'ve been communicated better.', date: daysFromNow(-176), isVerifiedNeighbor: false },
  { id: 'r42', businessId: 'b12', userId: 'rev-b12-0', userName: 'John R.', rating: 5, text: 'Fast, friendly, and thorough. Fresh Start Cleaning Co. is now our go-to for anything in this category.', date: daysFromNow(-15), isVerifiedNeighbor: true },
  { id: 'r43', businessId: 'b12', userId: 'rev-b12-1', userName: 'Brian C.', rating: 5, text: 'Fast, friendly, and thorough. Fresh Start Cleaning Co. is now our go-to for anything in this category.', date: daysFromNow(-205), isVerifiedNeighbor: false },
  { id: 'r44', businessId: 'b12', userId: 'rev-b12-2', userName: 'Megan B.', rating: 5, text: 'Fast, friendly, and thorough. Fresh Start Cleaning Co. is now our go-to for anything in this category.', date: daysFromNow(-185), isVerifiedNeighbor: false },
  { id: 'r45', businessId: 'b13', userId: 'rev-b13-0', userName: 'Mark T.', rating: 5, text: 'Triangle Air & Heat did an incredible job — on time, professional, and the results speak for themselves. Highly recommend to any neighbor.', date: daysFromNow(-192), isVerifiedNeighbor: true },
  { id: 'r46', businessId: 'b13', userId: 'rev-b13-1', userName: 'Mark S.', rating: 5, text: 'Fast, friendly, and thorough. Triangle Air & Heat is now our go-to for anything in this category.', date: daysFromNow(-135), isVerifiedNeighbor: false },
  { id: 'r47', businessId: 'b13', userId: 'rev-b13-2', userName: 'Kelly T.', rating: 5, text: 'Triangle Air & Heat did an incredible job — on time, professional, and the results speak for themselves. Highly recommend to any neighbor.', date: daysFromNow(-157), isVerifiedNeighbor: true },
  { id: 'r48', businessId: 'b14', userId: 'rev-b14-0', userName: 'Mark H.', rating: 3, text: 'It was okay — got the job done but not quite the wow factor I was expecting.', date: daysFromNow(-206), isVerifiedNeighbor: true },
  { id: 'r49', businessId: 'b14', userId: 'rev-b14-1', userName: 'Chris F.', rating: 3, text: 'Decent job from Bloom Interior Studio, but there were a couple of things that needed a follow-up visit.', date: daysFromNow(-203), isVerifiedNeighbor: true },
  { id: 'r50', businessId: 'b14', userId: 'rev-b14-2', userName: 'James F.', rating: 5, text: 'Best interior design experience we\'ve had in the neighborhood. Fair pricing and great communication the whole way through.', date: daysFromNow(-49), isVerifiedNeighbor: true },
  { id: 'r51', businessId: 'b14', userId: 'rev-b14-3', userName: 'Nicole W.', rating: 5, text: 'We\'ve used Bloom Interior Studio twice now and both times were flawless. They clearly care about doing the job right.', date: daysFromNow(-80), isVerifiedNeighbor: true },
  { id: 'r52', businessId: 'b15', userId: 'rev-b15-0', userName: 'Kevin H.', rating: 5, text: 'Fast, friendly, and thorough. Carolina Land & Garden is now our go-to for anything in this category.', date: daysFromNow(-75), isVerifiedNeighbor: true },
  { id: 'r53', businessId: 'b15', userId: 'rev-b15-1', userName: 'Kevin N.', rating: 4, text: 'Solid work overall from Carolina Land & Garden. A little pricier than expected but the quality was there.', date: daysFromNow(-46), isVerifiedNeighbor: false },
  { id: 'r54', businessId: 'b15', userId: 'rev-b15-2', userName: 'Kelly H.', rating: 3, text: 'Decent job from Carolina Land & Garden, but there were a couple of things that needed a follow-up visit.', date: daysFromNow(-40), isVerifiedNeighbor: false },
  { id: 'r55', businessId: 'b2', userId: 'rev-b2-0', userName: 'Eric R.', rating: 5, text: 'Fast, friendly, and thorough. GreenScape Lawns is now our go-to for anything in this category.', date: daysFromNow(-184), isVerifiedNeighbor: true },
  { id: 'r56', businessId: 'b2', userId: 'rev-b2-1', userName: 'Jessica S.', rating: 5, text: 'We\'ve used GreenScape Lawns twice now and both times were flawless. They clearly care about doing the job right.', date: daysFromNow(-155), isVerifiedNeighbor: false },
  { id: 'r57', businessId: 'b2', userId: 'rev-b2-2', userName: 'John T.', rating: 5, text: 'We\'ve used GreenScape Lawns twice now and both times were flawless. They clearly care about doing the job right.', date: daysFromNow(-13), isVerifiedNeighbor: true },
  { id: 'r58', businessId: 'b2', userId: 'rev-b2-3', userName: 'Nicole M.', rating: 5, text: 'Fast, friendly, and thorough. GreenScape Lawns is now our go-to for anything in this category.', date: daysFromNow(-113), isVerifiedNeighbor: false },
  { id: 'r59', businessId: 'b16', userId: 'rev-b16-0', userName: 'Paul R.', rating: 5, text: 'Oak City Movers did an incredible job — on time, professional, and the results speak for themselves. Highly recommend to any neighbor.', date: daysFromNow(-203), isVerifiedNeighbor: true },
  { id: 'r60', businessId: 'b16', userId: 'rev-b16-1', userName: 'Christine G.', rating: 5, text: 'Fast, friendly, and thorough. Oak City Movers is now our go-to for anything in this category.', date: daysFromNow(-168), isVerifiedNeighbor: false },
  { id: 'r61', businessId: 'b16', userId: 'rev-b16-2', userName: 'Greg R.', rating: 5, text: 'Fast, friendly, and thorough. Oak City Movers is now our go-to for anything in this category.', date: daysFromNow(-109), isVerifiedNeighbor: true },
  { id: 'r62', businessId: 'b16', userId: 'rev-b16-3', userName: 'Chris W.', rating: 4, text: 'Professional and got the job done. A few small things could\'ve been communicated better.', date: daysFromNow(-196), isVerifiedNeighbor: true },
  { id: 'r63', businessId: 'b17', userId: 'rev-b17-0', userName: 'Mike H.', rating: 5, text: 'Fast, friendly, and thorough. FreshCoat Painting Co. is now our go-to for anything in this category.', date: daysFromNow(-117), isVerifiedNeighbor: true },
  { id: 'r64', businessId: 'b17', userId: 'rev-b17-1', userName: 'Mike S.', rating: 5, text: 'Exceeded expectations. The crew was respectful of our property and cleaned up after themselves.', date: daysFromNow(-146), isVerifiedNeighbor: false },
  { id: 'r65', businessId: 'b17', userId: 'rev-b17-2', userName: 'Josh W.', rating: 5, text: 'We\'ve used FreshCoat Painting Co. twice now and both times were flawless. They clearly care about doing the job right.', date: daysFromNow(-26), isVerifiedNeighbor: true },
  { id: 'r66', businessId: 'b17', userId: 'rev-b17-3', userName: 'Brian S.', rating: 4, text: 'Happy with the results. Would use FreshCoat Painting Co. again for future projects.', date: daysFromNow(-120), isVerifiedNeighbor: true },
  { id: 'r67', businessId: 'b18', userId: 'rev-b18-0', userName: 'Paul S.', rating: 3, text: 'Decent job from GuardianBug Pest Control, but there were a couple of things that needed a follow-up visit.', date: daysFromNow(-200), isVerifiedNeighbor: true },
  { id: 'r68', businessId: 'b18', userId: 'rev-b18-1', userName: 'Chris T.', rating: 5, text: 'Best pest control experience we\'ve had in the neighborhood. Fair pricing and great communication the whole way through.', date: daysFromNow(-60), isVerifiedNeighbor: false },
  { id: 'r69', businessId: 'b18', userId: 'rev-b18-2', userName: 'Erin L.', rating: 5, text: 'Best pest control experience we\'ve had in the neighborhood. Fair pricing and great communication the whole way through.', date: daysFromNow(-12), isVerifiedNeighbor: false },
  { id: 'r70', businessId: 'b18', userId: 'rev-b18-3', userName: 'Kelly B.', rating: 5, text: 'We\'ve used GuardianBug Pest Control twice now and both times were flawless. They clearly care about doing the job right.', date: daysFromNow(-74), isVerifiedNeighbor: true },
  { id: 'r71', businessId: 'b19', userId: 'rev-b19-0', userName: 'Ashley R.', rating: 5, text: 'FlowRight Plumbing did an incredible job — on time, professional, and the results speak for themselves. Highly recommend to any neighbor.', date: daysFromNow(-154), isVerifiedNeighbor: true },
  { id: 'r72', businessId: 'b19', userId: 'rev-b19-1', userName: 'Lisa G.', rating: 5, text: 'Exceeded expectations. The crew was respectful of our property and cleaned up after themselves.', date: daysFromNow(-104), isVerifiedNeighbor: false },
  { id: 'r73', businessId: 'b19', userId: 'rev-b19-2', userName: 'Megan T.', rating: 5, text: 'Exceeded expectations. The crew was respectful of our property and cleaned up after themselves.', date: daysFromNow(-80), isVerifiedNeighbor: false },
  { id: 'r74', businessId: 'b19', userId: 'rev-b19-3', userName: 'Megan H.', rating: 4, text: 'Professional and got the job done. A few small things could\'ve been communicated better.', date: daysFromNow(-105), isVerifiedNeighbor: true },
  { id: 'r75', businessId: 'b19', userId: 'rev-b19-4', userName: 'Mike H.', rating: 5, text: 'Exceeded expectations. The crew was respectful of our property and cleaned up after themselves.', date: daysFromNow(-169), isVerifiedNeighbor: true },
  { id: 'r76', businessId: 'b1', userId: 'rev-b1-0', userName: 'Chris R.', rating: 4, text: 'Solid work overall from AquaPure Pools. A little pricier than expected but the quality was there.', date: daysFromNow(-67), isVerifiedNeighbor: false },
  { id: 'r77', businessId: 'b1', userId: 'rev-b1-1', userName: 'Paul W.', rating: 3, text: 'It was okay — got the job done but not quite the wow factor I was expecting.', date: daysFromNow(-84), isVerifiedNeighbor: true },
  { id: 'r78', businessId: 'b1', userId: 'rev-b1-2', userName: 'Steve K.', rating: 5, text: 'We\'ve used AquaPure Pools twice now and both times were flawless. They clearly care about doing the job right.', date: daysFromNow(-77), isVerifiedNeighbor: true },
  { id: 'r79', businessId: 'b1', userId: 'rev-b1-3', userName: 'Greg H.', rating: 4, text: 'Solid work overall from AquaPure Pools. A little pricier than expected but the quality was there.', date: daysFromNow(-145), isVerifiedNeighbor: true },
  { id: 'r80', businessId: 'b1', userId: 'rev-b1-4', userName: 'David K.', rating: 5, text: 'AquaPure Pools did an incredible job — on time, professional, and the results speak for themselves. Highly recommend to any neighbor.', date: daysFromNow(-184), isVerifiedNeighbor: false },
  { id: 'r81', businessId: 'b1', userId: 'rev-b1-5', userName: 'David C.', rating: 5, text: 'AquaPure Pools did an incredible job — on time, professional, and the results speak for themselves. Highly recommend to any neighbor.', date: daysFromNow(-107), isVerifiedNeighbor: true },
  { id: 'r82', businessId: 'b20', userId: 'rev-b20-0', userName: 'Christine F.', rating: 5, text: 'Fast, friendly, and thorough. BlastAway Power Washing is now our go-to for anything in this category.', date: daysFromNow(-62), isVerifiedNeighbor: false },
  { id: 'r83', businessId: 'b20', userId: 'rev-b20-1', userName: 'David D.', rating: 3, text: 'Decent job from BlastAway Power Washing, but there were a couple of things that needed a follow-up visit.', date: daysFromNow(-168), isVerifiedNeighbor: true },
  { id: 'r84', businessId: 'b20', userId: 'rev-b20-2', userName: 'Paul G.', rating: 4, text: 'Professional and got the job done. A few small things could\'ve been communicated better.', date: daysFromNow(-161), isVerifiedNeighbor: false },
  { id: 'r85', businessId: 'b21', userId: 'rev-b21-0', userName: 'Hannah P.', rating: 4, text: 'Happy with the results. Would use Summit Roofing Co. again for future projects.', date: daysFromNow(-170), isVerifiedNeighbor: false },
  { id: 'r86', businessId: 'b21', userId: 'rev-b21-1', userName: 'Chris F.', rating: 5, text: 'Best roofing experience we\'ve had in the neighborhood. Fair pricing and great communication the whole way through.', date: daysFromNow(-89), isVerifiedNeighbor: true },
  { id: 'r87', businessId: 'b21', userId: 'rev-b21-2', userName: 'Whitney F.', rating: 4, text: 'Professional and got the job done. A few small things could\'ve been communicated better.', date: daysFromNow(-74), isVerifiedNeighbor: false },
  { id: 'r88', businessId: 'b21', userId: 'rev-b21-3', userName: 'Eric S.', rating: 5, text: 'Summit Roofing Co. did an incredible job — on time, professional, and the results speak for themselves. Highly recommend to any neighbor.', date: daysFromNow(-109), isVerifiedNeighbor: false },
  { id: 'r89', businessId: 'b21', userId: 'rev-b21-4', userName: 'Rachel L.', rating: 5, text: 'Summit Roofing Co. did an incredible job — on time, professional, and the results speak for themselves. Highly recommend to any neighbor.', date: daysFromNow(-131), isVerifiedNeighbor: true },
  { id: 'r93', businessId: 'b23', userId: 'rev-b23-0', userName: 'Greg R.', rating: 4, text: 'Solid work overall from SunHarvest Solar. A little pricier than expected but the quality was there.', date: daysFromNow(-43), isVerifiedNeighbor: true },
  { id: 'r94', businessId: 'b23', userId: 'rev-b23-1', userName: 'Steve G.', rating: 5, text: 'Fast, friendly, and thorough. SunHarvest Solar is now our go-to for anything in this category.', date: daysFromNow(-122), isVerifiedNeighbor: true },
  { id: 'r95', businessId: 'b23', userId: 'rev-b23-2', userName: 'Whitney F.', rating: 5, text: 'Best solar panel installation experience we\'ve had in the neighborhood. Fair pricing and great communication the whole way through.', date: daysFromNow(-146), isVerifiedNeighbor: false },
  { id: 'r96', businessId: 'b24', userId: 'rev-b24-0', userName: 'Laura K.', rating: 3, text: 'Decent job from Heritage Tree Care, but there were a couple of things that needed a follow-up visit.', date: daysFromNow(-130), isVerifiedNeighbor: false },
  { id: 'r97', businessId: 'b24', userId: 'rev-b24-1', userName: 'Ashley L.', rating: 4, text: 'Professional and got the job done. A few small things could\'ve been communicated better.', date: daysFromNow(-70), isVerifiedNeighbor: true },
  { id: 'r98', businessId: 'b24', userId: 'rev-b24-2', userName: 'Mike N.', rating: 5, text: 'Fast, friendly, and thorough. Heritage Tree Care is now our go-to for anything in this category.', date: daysFromNow(-119), isVerifiedNeighbor: true },
  { id: 'r99', businessId: 'b25', userId: 'rev-b25-0', userName: 'Paul L.', rating: 5, text: 'Best window washing experience we\'ve had in the neighborhood. Fair pricing and great communication the whole way through.', date: daysFromNow(-88), isVerifiedNeighbor: true },
  { id: 'r100', businessId: 'b25', userId: 'rev-b25-1', userName: 'David L.', rating: 5, text: 'Exceeded expectations. The crew was respectful of our property and cleaned up after themselves.', date: daysFromNow(-88), isVerifiedNeighbor: false },
  { id: 'r101', businessId: 'b25', userId: 'rev-b25-2', userName: 'Brian S.', rating: 4, text: 'Professional and got the job done. A few small things could\'ve been communicated better.', date: daysFromNow(-100), isVerifiedNeighbor: true },
  { id: 'r102', businessId: 'b25', userId: 'rev-b25-3', userName: 'Whitney F.', rating: 4, text: 'Happy with the results. Would use CrystalView Window Cleaning again for future projects.', date: daysFromNow(-42), isVerifiedNeighbor: true },
  { id: 'r103', businessId: 'b25', userId: 'rev-b25-4', userName: 'Chris W.', rating: 5, text: 'Best window washing experience we\'ve had in the neighborhood. Fair pricing and great communication the whole way through.', date: daysFromNow(-149), isVerifiedNeighbor: false },
];

export const BUSINESSES: Business[] = [
  { id: 'b1', name: 'AquaPure Pools', logoUrl: getCategoryImage('Pool Maintenance', 200, 200), description: 'Your trusted neighborhood pool experts. We keep your water crystal clear year-round.', rating: 4.8, reviewCount: 124, galleryPhotoIds: ['1632759145351-1d592919f522', '1562259949-e8e7689d7828', '1585704032915-c3400ca199e7'], highlights: ['Family Owned'], memberships: ['Local Chamber of Commerce Member'], isLicensed: false, amenities: ['Free Estimates', 'Satisfaction Guarantee'] },
  { id: 'b2', name: 'GreenScape Lawns', logoUrl: getCategoryImage('Lawn Service', 200, 200), description: 'Professional landscaping and lawn care services dedicated to making your outdoors beautiful.', rating: 4.6, reviewCount: 89, galleryPhotoIds: ['1621905251189-08b45d6a269e', '1517842645767-c639042777db', '1502082553048-f009c37129b9'], highlights: ['Locally Owned'], memberships: [], isLicensed: false, amenities: ['Free Estimates', 'Senior & Military Discounts'] },
  { id: 'b3', name: 'SparkleClean Homes', logoUrl: getCategoryImage('House Cleaning', 200, 200), description: 'Top-tier residential cleaning services. We treat your home with the care it deserves.', rating: 4.9, reviewCount: 210, galleryPhotoIds: ['1527515637462-cff94eecc1ac', '1581094288338-2314dddb7ece', '1600607687644-c7171b42498f'], highlights: ['Woman Owned', 'Locally Owned'], memberships: ['Local Chamber of Commerce Member'], isLicensed: false, amenities: ['Satisfaction Guarantee', 'Eco-Friendly Products'] },
  ...GENERATED_BUSINESSES,
];

export const REVIEWS: Review[] = GENERATED_REVIEWS;

const MOCK_USERS: User[] = Array.from({ length: 20 }).map((_, i) => ({
  id: `mock-user-${i}`,
  name: `Neighbor ${i + 1}`,
  type: UserType.RESIDENT,
  avatarUrl: `https://ui-avatars.com/api/?name=Neighbor+${i + 1}&background=random`,
  neighborhoodId: DEMO_NEIGHBORHOOD_IDS[i % DEMO_NEIGHBORHOOD_IDS.length],
  wishlist: [],
  connections: [],
  connectionCode: `NEIGHBOR${i}`
}));

export const USERS: User[] = [
  { id: 'u2', name: 'Jane Doe', type: UserType.RESIDENT, avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop', neighborhoodId: PRIMARY_NEIGHBORHOOD_ID, wishlist: [], connections: [], connectionCode: 'JANE123' },
  { id: 'user-a', name: 'Alice S.', type: UserType.RESIDENT, avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop', neighborhoodId: PRIMARY_NEIGHBORHOOD_ID, wishlist: [], connections: [], connectionCode: 'ALICE123' },
  { id: 'user-b', name: 'Bob M.', type: UserType.RESIDENT, avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop', neighborhoodId: PRIMARY_NEIGHBORHOOD_ID, wishlist: [], connections: [], connectionCode: 'BOB123' },
  { id: 'user-c', name: 'Anonymous Neighbor', type: UserType.RESIDENT, avatarUrl: '', neighborhoodId: PRIMARY_NEIGHBORHOOD_ID, isAnonymous: true, wishlist: [], connections: [], connectionCode: 'ANON123' },
  ...MOCK_USERS
];

export const INITIAL_SERVICES: Service[] = GENERATED_SERVICES;
